/**
 * Capability governance.
 *
 * `requires` is mechanically generated by the SDK from actual usage, so the
 * validator's job is to prove the claim rather than trust it: derived usage
 * must be a subset of what the manifest declares. Under-reporting is an error
 * because a consumer that trusts an incomplete `requires` list will accept a
 * package it cannot actually honor, and then silently do nothing where the
 * creator expected an effect.
 */

import type { DiagnosticCollector } from "./diagnostics.ts";
import { canonicalStringArray } from "./canonical.ts";
import { allowsConfiguration, allowsDegradedConsumption } from "./policy.ts";
import type { CapabilityId, InspectionPolicy, PrefabManifest, SupportState } from "./types.ts";

const CAPABILITY_PATTERN = /^([A-Za-z0-9._]+)(?:\/([A-Za-z0-9._-]+))?@(\d+)$/;

export function parseCapabilityId(raw: string): CapabilityId | null {
  const match = CAPABILITY_PATTERN.exec(raw);
  if (!match) return null;
  return {
    raw,
    namespace: match[1],
    name: match[2],
    version: Number.parseInt(match[3], 10),
    // The `x.` prefix is reserved for experimental capabilities that must never
    // reach the marketplace.
    experimental: match[1] === "x" || match[1].startsWith("x."),
  };
}

export interface CapabilityAssessment {
  supportState: SupportState;
  /** Required capabilities this consumer does not support. */
  unsupported: readonly string[];
  /** May this consumer configure instances or republish? */
  configurable: boolean;
}

export function assessCapabilities(
  manifest: PrefabManifest,
  usedCapabilities: readonly string[],
  policy: InspectionPolicy,
  diagnostics: DiagnosticCollector,
): CapabilityAssessment {
  const declared = new Set<string>();
  const supported = new Set(policy.supportedCapabilities);
  const unsupported: string[] = [];

  for (const raw of manifest.requires) {
    const capability = parseCapabilityId(raw);
    if (!capability) {
      diagnostics.add(
        "NOOK-CAPABILITY-MALFORMED",
        "manifest.json#/requires",
        `Capability ${JSON.stringify(raw)} is not of the form namespace[/name]@version.`,
        { capability: raw },
      );
      continue;
    }
    declared.add(raw);

    if (capability.experimental && policy.marketplace) {
      diagnostics.add(
        "NOOK-CAPABILITY-EXPERIMENTAL-REJECTED",
        "manifest.json#/requires",
        `Capability ${raw} uses the reserved experimental x.* prefix. Packages published to the ` +
          "marketplace must not require experimental capabilities.",
        { capability: raw },
      );
    }

    // Capabilities are versioned independently: supporting color@1 says nothing
    // about color@2, so the match is on the exact identifier.
    if (!supported.has(raw)) {
      unsupported.push(raw);
      diagnostics.add(
        "NOOK-UNSUPPORTED-CAPABILITY",
        "manifest.json#/requires",
        `This consumer does not support required capability ${raw}. ` +
          (allowsDegradedConsumption(policy.role)
            ? "The package data is preserved and exposed, but it cannot be configured or republished."
            : "Normal consumption is rejected."),
        { capability: raw },
      );
    }
  }

  for (const used of usedCapabilities) {
    if (declared.has(used)) continue;
    diagnostics.add(
      "NOOK-CAPABILITY-UNDERREPORTED",
      "manifest.json#/requires",
      `The package uses ${used} but does not declare it. requires must be a sorted, deduplicated ` +
        `superset of actual usage; expected at least ` +
        `${JSON.stringify(canonicalStringArray([...manifest.requires, ...usedCapabilities]))}.`,
      { capability: used },
    );
  }

  const usedSet = new Set(usedCapabilities);
  for (const raw of declared) {
    if (usedSet.has(raw)) continue;
    diagnostics.add(
      "NOOK-CAPABILITY-UNUSED",
      "manifest.json#/requires",
      `Capability ${raw} is declared but no usage of it was discovered.`,
      { capability: raw },
    );
  }

  const supportState: SupportState = unsupported.length > 0 ? "unsupported-capability" : "supported";
  return {
    supportState,
    unsupported: unsupported.sort(),
    configurable: supportState === "supported" && allowsConfiguration(policy.role),
  };
}
